### PR TITLE
bump version

### PR DESCRIPTION
**Pull request by Hoto-Cocoa**
🎉

### CODE REVIEW

**Review by nulta — DISMISSED** [review]
:art:

**Comment by Hoto-Cocoa** [comment]
CI maybe fixed

**Review by Astro-CQM — APPROVED** [review]
Not LGTM :-1:

**Review by nulta — APPROVED** [review]
:art:
⭐ ⭐ ⭐ ⭐ 🌟  [4.5/5.0] 드립니다
#리뷰레포

**Comment by Hoto-Cocoa** [comment]
> Not LGTM 👎

🤔

**Pull request merged**
