### PR TITLE
release: 2024.5.0-hotomoe.9

### PR DESCRIPTION
**Pull request by ghost**
## What
Release new hotomoe version

## Why
New hotomoe version released

## Additional info (optional)
Google Analytics implemented

## Checklist
- [x] Read the [contribution guide](https://github.com/misskey-dev/misskey/blob/develop/CONTRIBUTING.md)
- [x] Test working in a local environment
- [ ] (If needed) Add story of storybook
- [ ] (If needed) Update CHANGELOG.md
- [ ] (If possible) Add tests

### CODE REVIEW

**Review by yom21c1020 — DISMISSED** [review]
(not)LGTM

**Review by Hoto-Cocoa — CHANGES_REQUESTED** [review]
I didn't changed my gender

**Comment by yom21c1020** [comment]
LGTM(really)

p.s. Cocoa Hoto is female.

**Review by Hoto-Cocoa — APPROVED** [review]
LGTM

**Comment by ghost** [comment]
needs to fix branch ruleset to merge

**Pull request merged**
