### PR TITLE
fix(MkAbuseReportWindow): Disable reporting if no category is specified

### LINKED ISSUE #38: 사유가 전혀 지정되지 않은 신고의 발송을 제한
### Summary

사유 또는 카테고리 중 하나라도 지정되지 않은 신고를 제한

### Purpose

신고 처리를 용이하게...?

### Do you want to implement this feature yourself?

- [x] Yes, I will implement this by myself and send a pull request

### PR DESCRIPTION
**Pull request by napyblock**
## What

fix #38 

## Why

Disable reporting if no category is specified

## Checklist
- [X] Read the [contribution guide](https://github.com/misskey-dev/misskey/blob/develop/CONTRIBUTING.md)
- [x] Test working in a local environment
- [ ] (If needed) Add story of storybook
- [ ] (If needed) Update CHANGELOG.md
- [ ] (If possible) Add tests

### CODE REVIEW

**Comment by SWREI** [comment]
API 변경 (백엔드 2차 검증) 필요

**Review by Astro-CQM — COMMENTED** [review]
괜찮긴 한데 API 검증 추가 후 병합 필요

**Comment by Astro-CQM** [comment]
일단 Merge 하고 나중에 따로 추가하는 걸로... 이거 포크였네

**Review by Astro-CQM — APPROVED** [review]
LGTVUHD+ (Powered by @nulta)

**Comment by nulta** [comment]
> LGTVUHD+ (Powered by @nulta)

Life's Good To Me 👍

**Pull request merged**
