### PR TITLE
release: v2024.5.0-hotomoe.3

### LINKED ISSUE #5: 서버 정보에 연합 페이지가 보이지 않도록
저희는 서버 간의 관계를 굳이 공개할 생각이 없습니다

### PR DESCRIPTION
**Pull request by Astro-CQM**
## What
Release new version

## Why
fix #5 

## Additional info (optional)
real
## Checklist
- [x] Read the [contribution guide](https://github.com/misskey-dev/misskey/blob/develop/CONTRIBUTING.md)
- [x] Test working in a local environment
- [ ] (If needed) Add story of storybook
- [ ] (If needed) Update CHANGELOG.md
- [ ] (If possible) Add tests

### CODE REVIEW

**Review by Hoto-Cocoa — DISMISSED** [review]
lgtm

**Review by seojangho — DISMISSED** [review]
LGTM.

**Review by nulta — DISMISSED** [review]
LGTV📺

**Review by nulta — APPROVED** [review]
LGTM* ✌️

**previously LGTVUHD📺*

**Pull request merged**
